import { GoogleGenAI, Type } from "@google/genai";
import { GameMessage, StructuredLessonContent, AuthUser, AIUpdateSource } from '../types';
import { AI_PROVIDERS, DEFAULT_PROVIDER_ID } from '../data/providers';

// Helper to get provider settings from localStorage
const getProviderSettings = (): { activeProviderId: string, apiKey: string | null } => {
    try {
        const userString = localStorage.getItem('learn-with-ai-user');
        if (!userString) return { activeProviderId: DEFAULT_PROVIDER_ID, apiKey: null };
        
        const user: AuthUser = JSON.parse(userString);
        const settingsKey = `learn-with-ai-provider-settings-v1-${user.id}`;
        const settingsString = localStorage.getItem(settingsKey);

        if (settingsString) {
            const settings = JSON.parse(settingsString);
            const activeProviderId = settings.activeProviderId || DEFAULT_PROVIDER_ID;
            const apiKey = settings.apiKeys?.[activeProviderId] || null;
            return { activeProviderId, apiKey };
        }
        return { activeProviderId: DEFAULT_PROVIDER_ID, apiKey: null };
    } catch (e) {
        console.error("Could not retrieve provider settings", e);
        return { activeProviderId: DEFAULT_PROVIDER_ID, apiKey: null };
    }
};


// Helper to get an AI client instance. Throws an error if the key is missing or provider is not supported.
const getAiClient = (): GoogleGenAI => {
    const { activeProviderId, apiKey } = getProviderSettings();

    if (activeProviderId !== 'gemini') {
        const provider = AI_PROVIDERS.find(p => p.id === activeProviderId);
        const providerName = provider ? provider.name : 'The selected provider';
        throw new Error(`ProviderNotImplemented: ${providerName} is not yet integrated. Please select Google Gemini in Settings to use AI features.`);
    }

    if (!apiKey) {
        throw new Error("APIKeyMissing: Gemini API key not found. Please set it in the Settings page.");
    }
    return new GoogleGenAI({ apiKey });
};

const MOCK_LESSON_CONTENT: StructuredLessonContent = {
  explanation: [
    "This is the first key point of the mock lesson. It would normally be generated by the Gemini API.",
    "This is the second key point, providing another piece of crucial information on the topic.",
    "Here is a third point, often used to elaborate on a nuance or detail.",
    "The fourth point might introduce a related concept or an important consideration.",
  ],
  realLifeScenarios: [
    "Scenario 1: Here is a practical application in the real world. For example, using this concept in e-commerce for recommendations.",
    "Scenario 2: Another example would be in healthcare, for diagnostic purposes.",
    "Scenario 3: A third use case can be found in finance for fraud detection."
  ],
  codeSnippet: {
    language: "python",
    code: `# This is a mock code snippet.
# In a real lesson, this would demonstrate the concept.
def mock_function(concept_parameter):
    """
    This function simulates the application of the lesson's concept.
    """
    print(f"Applying {concept_parameter} to a problem.")
    # ... more relevant code
    return True

mock_function("The Core Concept")`
  },
  exercises: [
    "How would you explain this concept to a non-technical person?",
    "What are the potential ethical implications of using this technology in Scenario 2?",
    "Can you think of a different industry where this concept could be applied? Describe the use case."
  ],
  sources: [
    { title: "Mock Source 1 - Example.com", uri: "#" },
    { title: "Mock Source 2 - Another-Example.com", uri: "#" },
  ]
};

const lessonSchema = {
  type: Type.OBJECT,
  properties: {
    explanation: {
      type: Type.ARRAY,
      description: 'A list of 4-5 key points explaining the core concept. Each point should be a concise sentence or two. Use markdown for emphasis (e.g., **bold** text).',
      items: { type: Type.STRING }
    },
    realLifeScenarios: {
      type: Type.ARRAY,
      description: 'A list of 2-3 practical, real-world applications of the concept. Each item should be a string that might include markdown for emphasis.',
      items: { type: Type.STRING }
    },
    codeSnippet: {
      type: Type.OBJECT,
      description: 'A relevant Python code snippet. If not applicable, language should be "text" and code should state that no snippet is necessary.',
      properties: {
        language: { 
            type: Type.STRING,
            description: "The programming language of the code snippet, e.g., 'python'."
        },
        code: { 
            type: Type.STRING,
            description: "The actual code text. If not applicable, this should contain a sentence explaining why."
        }
      },
      required: ['language', 'code']
    },
    exercises: {
      type: Type.ARRAY,
      description: 'A list of 2-3 thought-provoking, open-ended questions to test understanding.',
      items: { type: Type.STRING }
    },
     sources: {
        type: Type.ARRAY,
        description: "A list of 2-3 credible web sources (URLs and titles) that could be used for further reading. If no specific external sources are needed, this can be an empty array.",
        items: {
            type: Type.OBJECT,
            properties: {
                title: { type: Type.STRING, description: "The title of the source webpage." },
                uri: { type: Type.STRING, description: "The full URL of the source." }
            },
            required: ['title', 'uri']
        }
    }
  },
  required: ['explanation', 'realLifeScenarios', 'codeSnippet', 'exercises', 'sources']
};


export const generateLessonContent = async (subLessonTitle: string, topicTitle: string): Promise<StructuredLessonContent> => {
    try {
        const ai = getAiClient();
        
        const prompt = `You are an expert AI educator creating a lesson plan.
Your task is to generate the content for a micro-lesson on the topic: "${subLessonTitle}" which is part of a larger module on "${topicTitle}".

Please generate a comprehensive, accurate, and easy-to-understand lesson.
The explanation should be a list of 4-5 bullet points, making it easy to digest.
The content must be structured according to the provided JSON schema.
For the sources, provide credible websites from your training data or state they are not needed.
Respond ONLY with the JSON object.`;
        
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: lessonSchema,
            },
        });
        
        const jsonResponse = JSON.parse(response.text);

        if (jsonResponse.explanation && Array.isArray(jsonResponse.explanation) && jsonResponse.realLifeScenarios && jsonResponse.codeSnippet && jsonResponse.exercises) {
             return jsonResponse as StructuredLessonContent;
        } else {
            console.error("Received malformed lesson data from AI:", jsonResponse);
            throw new Error('The AI returned data in an unexpected format.');
        }

    } catch (error: any) {
        console.error("Error generating lesson content:", error);
        if (error.message.startsWith("APIKeyMissing")) {
            return new Promise(resolve => setTimeout(() => resolve(MOCK_LESSON_CONTENT), 1000));
        }
        if (error.message.startsWith("ProviderNotImplemented")) {
            throw error;
        }
        if (error instanceof SyntaxError) {
             throw new Error("Failed to parse JSON response from the AI. The model may have returned invalid JSON.");
        }
        throw new Error("Failed to generate lesson content from AI.");
    }
};

export const generateGameResponse = async (history: GameMessage[], topicTitle: string, difficulty: string): Promise<string> => {
    try {
        const ai = getAiClient();
        
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: history.map(msg => ({ role: msg.role, parts: [{ text: msg.content }] })),
            config: {
                systemInstruction: `You are a Game Master for 'AI Venture', a text-based RPG where the player must solve problems using their knowledge of Artificial Intelligence.
Your goal is to create an engaging story that presents realistic scenarios related to the topic of "${topicTitle}" at a "${difficulty}" difficulty.
The game begins with the player as a new AI engineer at "Synapse Corp". Your first response MUST be the introduction and the first challenge.
For subsequent turns, evaluate the player's text response. Your response must describe the outcome of their action and present the next part of the story.

**IMPORTANT RULES:**
- **BE CONCISE:** Your responses must be extremely short and to the point (1-2 very short paragraphs).
- **FOCUS ON ACTION:** Immediately present the challenge or the outcome.
- **NO FLUFF:** Do not describe scenery, the character's internal thoughts, or unnecessary details. Focus on direct action, dialogue, and clear choices.
- Use markdown for emphasis (e.g., bold text).`
            }
        });
        
        return response.text;
    } catch (error: any) {
        console.error("Error generating game response:", error);
        if (error.message.startsWith("APIKeyMissing")) {
            if (history.length === 0) {
                return new Promise(resolve => setTimeout(() => resolve(`(Mock Response) Welcome to **Synapse Corp**! You're a new hire focusing on **${topicTitle}**. Your first task is a classic **${difficulty}**-level problem: a recommendation engine is stuck in a feedback loop. How do you approach this? \n\n*To get real AI responses, please add your Gemini API Key in Settings.*`), 500));
            }
            return new Promise(resolve => setTimeout(() => resolve("(Mock Response) Your action has an interesting consequence... The system seems to respond, but a new, unexpected problem arises. What is your next move?"), 500));
        }
        if (error.message.startsWith("ProviderNotImplemented")) {
            throw error;
        }
        throw new Error("Failed to get response from AI Game Master.");
    }
};

export const generateSimplifiedExplanation = async (lessonTitle: string, topicTitle: string, originalExplanation: string[]): Promise<string> => {
    try {
        const ai = getAiClient();
        
        const simplifiedExplanationSchema = {
          type: Type.ARRAY,
          items: {
            type: Type.STRING,
            description: "A single, simple bullet point explaining a part of the concept. Use a relatable analogy. Keep it concise."
          }
        };
        
        const prompt = `You are an expert communicator who can explain complex topics in a very simple and structured way.
Your task is to simplify the concept of "${lessonTitle}" (from the main topic of "${topicTitle}") for a complete beginner.

**Your goal:**
- Break down the concept into 3-4 simple, easy-to-digest bullet points.
- Use relatable analogies instead of technical jargon.
- Keep each point short and concise.
- The tone should be friendly and encouraging.

Here is the original technical explanation for context:
- ${originalExplanation.join("\n- ")}

Respond ONLY with a JSON array of strings that follows the provided schema.`;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: simplifiedExplanationSchema
            },
        });
        
        const points: string[] = JSON.parse(response.text);
        
        if (!Array.isArray(points)) {
            console.error("Simplified explanation from AI was not an array:", points);
            throw new Error("AI returned data in an unexpected format.");
        }
        
        // Convert the array of points into a markdown list string
        return points.map(point => `* ${point}`).join('\n');

    } catch (error: any)
    {
        console.error("Error generating simplified explanation:", error);
        if (error.message.startsWith("APIKeyMissing")) {
            return new Promise(resolve => setTimeout(() => resolve(`(Mock Response) Here's a simplified take on **${lessonTitle}**:
*   Imagine it's like a recipe. You follow simple steps to get a result.
*   Think of it as a smart assistant that's really good at one specific task.
*   It learns from lots of examples, just like you do when you're learning something new.

*To get real AI responses, please add your Gemini API Key in Settings.*`), 500));
        }
        if (error.message.startsWith("ProviderNotImplemented")) {
            throw error;
        }
        if (error instanceof SyntaxError) {
             throw new Error("Failed to parse JSON response from the AI. The model may have returned invalid JSON.");
        }
        throw new Error("Failed to get simplified explanation from AI.");
    }
};

export const generateAIUpdatesSummary = async (
    detailLevel: 'short' | 'medium' | 'detailed'
): Promise<{ summary: string; sources: AIUpdateSource[] }> => {
    try {
        const ai = getAiClient();
        const timeFrame = 'in the past week';

        let prompt = '';
        switch (detailLevel) {
            case 'short':
                prompt = `Provide a very brief, high-level summary of the most significant AI news and updates ${timeFrame}. Focus on the top 3-4 most impactful events. Be concise but maintain high quality. Use markdown for formatting, like headings and bullet points.`;
                break;
            case 'detailed':
                 prompt = `Provide a comprehensive and detailed overview of all major AI news and updates ${timeFrame}. Break down the information into sections (e.g., 'Large Language Models', 'Computer Vision', 'Industry Adoption'). Be as thorough as possible. Use markdown for formatting, like headings and bullet points.`;
                break;
            case 'medium':
            default:
                prompt = `Provide a medium-length summary of the most important AI news and updates ${timeFrame}. Cover the key developments across different areas like LLMs, generative models, research breakthroughs, and major product releases. Use markdown for formatting, like headings and bullet points.`;
                break;
        }

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                tools: [{googleSearch: {}}],
            }
        });

        const summary = response.text;
        const groundingMetadata = response.candidates?.[0]?.groundingMetadata;

        const sources: AIUpdateSource[] = groundingMetadata?.groundingChunks
            ?.filter(chunk => chunk.web?.uri) // Filter for chunks that have a web object with a uri
            .map(chunk => ({
                web: {
                    uri: chunk.web!.uri!, // Known to exist due to filter
                    title: chunk.web!.title || chunk.web!.uri!, // Fallback for title
                }
            })) || [];

        return { summary, sources };
    } catch (error: any) {
        console.error("Error generating AI updates summary:", error);
        if (error.message.startsWith("APIKeyMissing")) {
            const mockSummary = `(Mock Response) Here is a **${detailLevel}** summary of AI events from the past week.
*   **Major LLM Release:** A new large language model was announced, promising better reasoning.
*   **Image Generation Breakthrough:** A novel technique for creating photorealistic images was published.

*To get real AI responses, please add your Gemini API Key in Settings.*`;
            const mockSources: AIUpdateSource[] = [
                { web: { uri: "#", title: "Mock Source: AI News Today" } },
                { web: { uri: "#", title: "Mock Source: Tech Chronicle" } }
            ];
            return new Promise(resolve => setTimeout(() => resolve({ summary: mockSummary, sources: mockSources }), 500));
        }
         if (error.message.startsWith("ProviderNotImplemented")) {
            throw error;
        }
        throw new Error("Failed to get AI Updates from the web.");
    }
};
